use_frameworks!

target 'devicescloud' do
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'SnapKit', '~> 3.0.2'
    pod 'PullToRefreshSwift'
    pod 'Kingfisher', '~> 3.2.1'
    pod 'ALCameraViewController'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Toaster', '~> 2.0'
    pod 'WebViewJavascriptBridge', '~> 5.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'XCGLogger', '~> 4.0.0'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKPlatforms/Copy'
end
